[programs.devnet]
gif_collector = "GkjFCqkgzii2jNYfvCyYRt2m5WvVcaWKS2iDGGePizW5"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/codespace/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
